# Generated by Django 5.0.6 on 2024-06-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="main/static/image/default-avatar.png",
                upload_to="main/media/images/avatars/",
            ),
        ),
    ]
