# Generated by Django 5.0.7 on 2024-08-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
    ]
