# Generated by Django 5.0.7 on 2024-08-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_userprofile_last_login'),
        ('topic', '0015_rename_topicfollows_topicfollow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_topics',
            field=models.ManyToManyField(related_name='followers', through='topic.TopicFollow', to='topic.room'),
        ),
    ]
