# Generated by Django 5.0.8 on 2024-08-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile_followed_topics'),
        ('topic', '0017_answersfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_answers',
            field=models.ManyToManyField(related_name='followers', through='topic.AnswersFollow', to='topic.answersroom'),
        ),
    ]
