# Generated by Django 5.0.6 on 2024-06-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Room",
        ),
    ]
