# Generated by Django 5.0.7 on 2024-07-12 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0006_commentsroom_reply_to_alter_commentsroom_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsroom",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
