# Generated by Django 5.0.7 on 2024-07-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0007_alter_commentsroom_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersroom",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
    ]
