# Generated by Django 5.0.7 on 2024-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0008_answersroom_comment_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answersroom",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="commentsroom",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="commentsroom",
            name="reply_to_comment_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
