# Generated by Django 5.0.7 on 2024-07-23 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0010_commentsroom_father_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsroom",
            name="reply_to_comment_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="topic.commentsroom",
            ),
        ),
    ]
