# Generated by Django 5.0.7 on 2024-07-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0011_alter_commentsroom_reply_to_comment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsroom",
            name="father_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="topic.commentsroom",
                verbose_name="father comment",
            ),
        ),
        migrations.AlterField(
            model_name="commentsroom",
            name="reply_to_comment_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply_to_comment",
                to="topic.commentsroom",
            ),
        ),
    ]
