# Generated by Django 5.0.7 on 2024-08-22 09:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0014_topicfollows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicFollows',
            new_name='TopicFollow',
        ),
        migrations.AlterModelOptions(
            name='topicfollow',
            options={'ordering': ['-follow_at']},
        ),
        migrations.RenameField(
            model_name='topicfollow',
            old_name='room',
            new_name='topic_room',
        ),
        migrations.AlterUniqueTogether(
            name='topicfollow',
            unique_together={('user', 'topic_room')},
        ),
    ]
