# Generated by Django 5.0.8 on 2024-08-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0017_answersfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersfollow',
            name='approve_status',
            field=models.CharField(choices=[('approved', 'disapproved'), ('none', 'none'), ('disapproved', 'disapproved')], default='none', max_length=12),
        ),
    ]
