# Generated by Django 5.0.8 on 2024-08-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0018_answersfollow_approve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersfollow',
            name='approve_status',
            field=models.CharField(choices=[('approved', 'disapproved'), ('disapproved', 'disapproved')], default='none', max_length=12),
        ),
    ]
